### PR TITLE
Update jumpstart-launch-tasks.sh

### PR DESCRIPTION
**Pull request by sherakama**
Multistack.

### CODE REVIEW

**Comment by jbickar** [comment]
In 7+ years, I have never "launched" a people site.

**Comment by sherakama** [comment]
Fair nuff.

**Comment by jbickar** [comment]
LOL. Sorry for the makework. Your intentions were pure.

**Comment by sherakama** [comment]
It was fine, I did all my edits through the GitHub UI and I was going to have you debug it. 😆

**Comment by jbickar** [comment]
I know how you roll.

**Comment by sherakama** [comment]
No comment on the branch name tho? I am disappointed.

**Comment by jbickar** [comment]
I was curious, but it went over my head.

**Comment by sherakama** [comment]
Only one of the greats: https://www.youtube.com/watch?v=9jWGbvemTag

**Comment by jbickar** [comment]
I wish I could say that was before my time, but I am not familiar with that movie.

**Pull request closed without merging**
