### PR TITLE
DEVOPS-000: remove site 10711

### PR DESCRIPTION
**Pull request by jbickar**
Errors with site 10711. Not sure which site that was, but it no longer exists.

https://www.cardinalsites.acsitefactory.com/sites-by-group/grid?field_codebase_value=All&nodes=&users=&custom_theme_count=&disk_space=&field_domain_contains=10711&field_domain_value_1=&uid=&nid=

### CODE REVIEW

**Comment by imonroe** [comment]
I have one more to add, but waiting on confirmation of which one they want.

**Review by imonroe — COMMENTED** [review]
Ok, my two changes are in.

**Comment by jbickar** [comment]
* https://www.cardinalsites.acsitefactory.com/sites-by-group/grid?field_codebase_value=All&nodes=&users=&custom_theme_count=&disk_space=&field_domain_contains=&field_domain_value_1=&uid=&nid=18316
* https://www.cardinalsites.acsitefactory.com/sites-by-group/grid?field_codebase_value=All&nodes=&users=&custom_theme_count=&disk_space=&field_domain_contains=&field_domain_value_1=&uid=&nid=13751

**Comment by jbickar** [comment]
Shortnames `share` and `scits`. I approve your changes.

**Pull request merged**
